import type { Product } from './types'

export const products: Product[] = [
  {
    id: 'hoodie-zadyhayus',
    slug: 'hoodie-zadyhayus',
    name: 'Худи «Задыхаюсь»',
    nameUz: 'Hoodie "Bo\'g\'ilaman"',
    price: 670000,
    image: '/products/hoodie-zadyhayus.jpg',
    imageBg: '#3a3a4e',
    tag: 'art',
    collab: 'Kuznetsovs Gallery',
    category: 'clothing',
    collection: 'vozduh',
    description: 'Адрас и противогаз. Ташкентская башня в смоге. Художник Kuznetsovs Gallery нарисовал то, что мы все чувствуем, но не говорим вслух. Click запустил Yashil Meros, чтобы это изменить.',
    isAvailable: true,
    cashbackPercent: 5,
    season: 'all',
    yashilMeros: true,
  },
  {
    id: 'tshirt-zadyhayus',
    slug: 'tshirt-zadyhayus',
    name: 'Футболка «Задыхаюсь»',
    price: 395000,
    image: '/products/tshirt-zadyhayus.jpg',
    imageBg: '#3a3a4e',
    tag: 'art',
    collab: 'Kuznetsovs Gallery',
    category: 'clothing',
    collection: 'vozduh',
    description: 'Адрас и противогаз. Лёгкий хлопок для ташкентского лета. QR-код сзади → проект Yashil Meros.',
    isAvailable: true,
    cashbackPercent: 5,
    season: 'summer',
    yashilMeros: true,
  },
  {
    id: 'hoodie-molchanie',
    slug: 'hoodie-molchanie',
    name: 'Худи «Молчание империи»',
    price: 670000,
    image: '/products/hoodie-molchanie.jpg',
    imageBg: '#3d2010',
    tag: 'limited',
    collab: 'Kuznetsovs Gallery',
    category: 'clothing',
    collection: 'molchanie',
    description: 'Амир Тимур в маске. Потому что даже он бы надел. Ташкент в топ-10 городов с худшим воздухом. Лимитированная коллекция.',
    isAvailable: false, // скрыт до 1 сентября
    cashbackPercent: 5,
    season: 'autumn',
    yashilMeros: false,
  },
  {
    id: 'sweatshirt-molchanie',
    slug: 'sweatshirt-molchanie',
    name: 'Свитшот «Молчание империи»',
    price: 570000,
    image: '/products/sweatshirt-molchanie.jpg',
    imageBg: '#3d2010',
    tag: 'limited',
    collab: 'Kuznetsovs Gallery',
    category: 'clothing',
    collection: 'molchanie',
    description: 'Амир Тимур в маске. Лимитированная осенняя коллекция ко Дню Независимости.',
    isAvailable: false, // скрыт до 1 сентября
    cashbackPercent: 5,
    season: 'autumn',
    yashilMeros: false,
  },
  {
    id: 'tshirt-put',
    slug: 'tshirt-put',
    name: 'Футболка «Путь»',
    price: 395000,
    image: '/products/tshirt-put.jpg',
    imageBg: '#1a3520',
    tag: 'eco',
    collab: 'Kuznetsovs Gallery',
    category: 'clothing',
    collection: 'yashil',
    description: 'Человек на ишаке везёт дерево через серый город. Кислородная маска — чтобы доехать. QR сзади → Yashil Meros.',
    isAvailable: true,
    cashbackPercent: 5,
    season: 'summer',
    yashilMeros: true,
  },
  {
    id: 'sweatshirt-rost',
    slug: 'sweatshirt-rost',
    name: 'Свитшот «Рост»',
    price: 570000,
    image: '/products/sweatshirt-rost.jpg',
    imageBg: '#4a7a20',
    tag: 'eco',
    collab: 'Kuznetsovs Gallery',
    category: 'clothing',
    collection: 'yashil',
    description: 'Сад, где у каждого дерева есть имя — Timur, Sevara, Алексей. Это реальные люди из Yashil Meros. Осенняя коллекция.',
    isAvailable: false, // трёхнитка — до сентября
    cashbackPercent: 5,
    season: 'autumn',
    yashilMeros: true,
  },
  {
    id: 'wallet-keys',
    slug: 'wallet-keys',
    name: 'Кошелёк «Карты Деньги 2 Ключа»',
    price: 285000,
    image: '/products/wallet-keys.jpg',
    imageBg: '#e8eaf0',
    tag: 'leather',
    collab: 'Мастера Ташкента',
    category: 'leather',
    description: 'Сделан руками ташкентских мастеров. Три отдела — карты, наличные, ключи. Натуральная кожа, логотип Click тиснением.',
    isAvailable: true,
    cashbackPercent: 3,
    season: 'all',
    yashilMeros: false,
  },
  {
    id: 'avoska-yashil',
    slug: 'avoska-yashil',
    name: 'Авоська Yashil Meros',
    price: 90000,
    image: '/products/avoska.jpg',
    imageBg: '#e8e4d8',
    tag: 'new',
    collab: 'Ручная работа',
    category: 'eco',
    description: 'Рыболовная сетка + винтажная ткань. Вместо пластика. Каждая авоська заменяет ~200 пакетов в год. QR → посадить дерево через Click.',
    isAvailable: true,
    cashbackPercent: 3,
    season: 'all',
    yashilMeros: true,
  },
  {
    id: 'ushanka-set',
    slug: 'ushanka-set',
    name: 'Ушанка + варежки на шнурке',
    price: 500000,
    image: '/products/ushanka.jpg',
    imageBg: '#1a1410',
    tag: 'new',
    category: 'clothing',
    description: 'Пушистый комплект — ушанка и варежки на шнурке. Зимняя коллекция Click.',
    isAvailable: false, // скрыт до октября
    cashbackPercent: 5,
    season: 'winter',
    yashilMeros: false,
  },
]

// Только доступные сейчас
export const availableProducts = products.filter(p => p.isAvailable)

// По категориям
export const getProductsByCategory = (category: string) =>
  availableProducts.filter(p => category === 'all' || p.category === category)
