import type { Product } from './types'

const CDN = 'https://robosell.ams3.digitaloceanspaces.com/robosell'

export const products: Product[] = [

  // ─── КОЛЛАБОРАЦИИ ───────────────────────────────────────────────────────────

  {
    id: 'tshirt-close-friends',
    slug: 'tshirt-close-friends',
    name: 'Футболка «Close Friends × Click»',
    nameUz: 'Futbolka "Close Friends × Click"',
    price: 200000,
    image: `${CDN}/product/591361-800351.webp`,
    imageBg: '#f0ede8',
    tag: 'collab',
    collab: 'Close Friends',
    category: 'clothing',
    collection: 'collabs',
    description: 'Футболка из 82% натурального хлопка. Глубокий чёрный цвет и лаконичный дизайн. Коллаборация Click × Close Friends.',
    isAvailable: true,
    cashbackPercent: 5,
    season: 'all',
    yashilMeros: false,
  },
  {
    id: 'tshirt-sublimation',
    slug: 'tshirt-sublimation',
    name: 'Футболка «Sublimation × Click»',
    nameUz: 'Futbolka "Sublimation × Click"',
    price: 200000,
    image: `${CDN}/product/608902-866032.webp`,
    imageBg: '#f0ede8',
    tag: 'collab',
    collab: 'Sublimation',
    category: 'clothing',
    collection: 'collabs',
    description: 'Футболка из 82% натурального хлопка. Коллаборация Click × Sublimation.',
    isAvailable: true,
    cashbackPercent: 5,
    season: 'all',
    yashilMeros: false,
  },

  // ─── КОЛЛЕКЦИЯ YASHIL MEROS ─────────────────────────────────────────────────

  {
    id: 'hoodie-zadyhayus',
    slug: 'hoodie-zadyhayus',
    name: 'Худи «Задыхаюсь»',
    nameUz: 'Hoodie "Bo\'g\'ilyapman"',
    price: 670000,
    image: `${CDN}/c19e7e45-4df1-45f3-a9cc-24d2ee813327.webp`,
    imageBg: '#f0ede8',
    tag: 'art',
    collab: 'Kuznetsovs Gallery',
    category: 'clothing',
    collection: 'vozduh',
    description: 'Адрас и противогаз. Ташкентская башня в смоге. Художник Kuznetsovs Gallery нарисовал то, что мы все чувствуем, но не говорим вслух. Click запустил Yashil Meros, чтобы это изменить.',
    isAvailable: true,
    cashbackPercent: 5,
    season: 'all',
    yashilMeros: true,
  },
  {
    id: 'hoodie-molchanie',
    slug: 'hoodie-molchanie',
    name: 'Худи «Молчание империи»',
    nameUz: 'Hoodie "Jimjitlik imperiyasi"',
    price: 670000,
    image: `${CDN}/92653c67-774e-4d81-8d13-2a11fec88d56.webp`,
    imageBg: '#f0ede8',
    tag: 'limited',
    collab: 'Kuznetsovs Gallery',
    category: 'clothing',
    collection: 'molchanie',
    description: 'Амир Тимур в маске. Потому что даже он бы надел. Ташкент в топ-10 городов с худшим воздухом. Лимитированная коллекция. Цвет: шоколад.',
    isAvailable: true,
    cashbackPercent: 5,
    season: 'autumn',
    yashilMeros: false,
  },
  {
    id: 'hoodie-oblako',
    slug: 'hoodie-oblako',
    name: 'Худи «Облако жадности»',
    nameUz: 'Hoodie "Ochofatlik buluti"',
    price: 670000,
    image: `${CDN}/3a4c29ba-cf0f-47ed-9749-b6be30d18c2e.webp`,
    imageBg: '#f0ede8',
    tag: 'art',
    collab: 'Kuznetsovs Gallery',
    category: 'clothing',
    collection: 'vozduh',
    description: 'Доллары в узбекских орнаментах внутри чёрного облака из смога. Арт-принт Kuznetsovs Gallery. Цвет: светло-серый.',
    isAvailable: false,
    cashbackPercent: 5,
    season: 'all',
    yashilMeros: true,
  },
  {
    id: 'tshirt-zadyhayus',
    slug: 'tshirt-zadyhayus',
    name: 'Футболка «Задыхаюсь»',
    nameUz: 'Futbolka "Bo\'g\'ilyapman"',
    price: 395000,
    image: `${CDN}/3f2d4024-60d7-4ff7-a5db-0bdc28e24072.webp`,
    imageBg: '#f0ede8',
    tag: 'art',
    collab: 'Kuznetsovs Gallery',
    category: 'clothing',
    collection: 'vozduh',
    description: 'Фигура в узбекском адрасе с кислородной маской. QR-код «нажми ради кислорода». 100% хлопок, унисекс. Цвет: тёмно-серый.',
    isAvailable: true,
    cashbackPercent: 5,
    season: 'summer',
    yashilMeros: true,
  },
  {
    id: 'tshirt-molchanie',
    slug: 'tshirt-molchanie',
    name: 'Футболка «Молчание империи»',
    nameUz: 'Futbolka "Jimjitlik imperiyasi"',
    price: 395000,
    image: `${CDN}/95114ea6-88bc-4cdc-9085-4aeff3b316bb.webp`,
    imageBg: '#f0ede8',
    tag: 'limited',
    collab: 'Kuznetsovs Gallery',
    category: 'clothing',
    collection: 'molchanie',
    description: 'Монумент Амира Тимура в маске. Арт-принт Kuznetsovs Gallery. 100% хлопок, унисекс. Цвет: шоколад.',
    isAvailable: true,
    cashbackPercent: 5,
    season: 'summer',
    yashilMeros: false,
  },
  {
    id: 'tshirt-oblako',
    slug: 'tshirt-oblako',
    name: 'Футболка «Облако жадности»',
    nameUz: 'Futbolka "Ochofatlik buluti"',
    price: 395000,
    image: `${CDN}/fdae2bf0-2227-409e-bdb0-8b95ec9aba52.webp`,
    imageBg: '#f0ede8',
    tag: 'art',
    collab: 'Kuznetsovs Gallery',
    category: 'clothing',
    collection: 'vozduh',
    description: 'Доллары в узбекских орнаментах внутри чёрного облака смога. Арт-принт Kuznetsovs Gallery. 100% хлопок. Цвет: светло-серый.',
    isAvailable: true,
    cashbackPercent: 5,
    season: 'summer',
    yashilMeros: true,
  },
  {
    id: 'tshirt-put',
    slug: 'tshirt-put',
    name: 'Футболка «Путь»',
    nameUz: 'Futbolka "Yo\'l"',
    price: 395000,
    originalPrice: 570000,
    image: `${CDN}/a46f6e53-253b-402d-aee1-095688cdba83.webp`,
    imageBg: '#f0ede8',
    tag: 'eco',
    collab: 'Kuznetsovs Gallery',
    category: 'clothing',
    collection: 'yashil',
    description: 'Футболка о начале пути. Арт-принт Kuznetsovs Gallery. 100% хлопок, унисекс.',
    isAvailable: false,
    cashbackPercent: 5,
    season: 'summer',
    yashilMeros: true,
  },
  {
    id: 'tshirt-rost',
    slug: 'tshirt-rost',
    name: 'Футболка «Рост»',
    nameUz: 'Futbolka "O\'sish"',
    price: 395000,
    image: `${CDN}/34a704fc-c93c-4fb7-a3f4-fd85ee5217a3.webp`,
    imageBg: '#f0ede8',
    tag: 'eco',
    collab: 'Kuznetsovs Gallery',
    category: 'clothing',
    collection: 'yashil',
    description: '«Рост начинается там, где действие становится привычкой.» Арт-принт Kuznetsovs Gallery. 100% хлопок, унисекс. Цвет: ярко-зелёный.',
    isAvailable: false,
    cashbackPercent: 5,
    season: 'summer',
    yashilMeros: true,
  },
  {
    id: 'sweatshirt-molchanie',
    slug: 'sweatshirt-molchanie',
    name: 'Свитшот «Молчание империи»',
    nameUz: 'Svitshot "Jimjitlik imperiyasi"',
    price: 570000,
    image: `${CDN}/9872aa2e-e5d5-4fc3-b7f0-5202c9a159cc.webp`,
    imageBg: '#f0ede8',
    tag: 'limited',
    collab: 'Kuznetsovs Gallery',
    category: 'clothing',
    collection: 'molchanie',
    description: 'Монумент Амира Тимура в маске. Коллекция «Воздух, в котором мы дышим». Цвет: шоколад.',
    isAvailable: true,
    cashbackPercent: 5,
    season: 'autumn',
    yashilMeros: false,
  },
  {
    id: 'sweatshirt-put',
    slug: 'sweatshirt-put',
    name: 'Свитшот «Путь»',
    nameUz: 'Svitshot "Yo\'l"',
    price: 570000,
    image: `${CDN}/0197838e-764b-4efb-b53c-a9592f8208c7.webp`,
    imageBg: '#f0ede8',
    tag: 'eco',
    collab: 'Kuznetsovs Gallery',
    category: 'clothing',
    collection: 'yashil',
    description: 'Свитшот о начале. Глубокий зелёный — цвет устойчивости. «Каждое большое изменение начинается с одного дерева.»',
    isAvailable: false,
    cashbackPercent: 5,
    season: 'autumn',
    yashilMeros: true,
  },
  {
    id: 'sweatshirt-rost',
    slug: 'sweatshirt-rost',
    name: 'Свитшот «Рост»',
    nameUz: 'Svitshot "O\'sish"',
    price: 570000,
    image: `${CDN}/540d1879-a42f-4ae2-854d-5be0e90daedc.webp`,
    imageBg: '#f0ede8',
    tag: 'eco',
    collab: 'Kuznetsovs Gallery',
    category: 'clothing',
    collection: 'yashil',
    description: '«Рост начинается там, где действие становится привычкой.» Цвет: ярко-зелёный.',
    isAvailable: false,
    cashbackPercent: 5,
    season: 'autumn',
    yashilMeros: true,
  },
  {
    id: 'tshirt-oblako-una',
    slug: 'tshirt-oblako-una',
    name: 'Футболка «Облако» by UNA',
    nameUz: 'Futbolka "Bulut" by UNA',
    price: 550000,
    image: `${CDN}/d61cc327-486c-4d22-a745-a3f72945472b.jpg`,
    imageBg: '#f0ede8',
    tag: 'collab',
    collab: 'UNA',
    category: 'clothing',
    collection: 'collabs',
    description: 'Оверсайз, 100% хлопок, цвет айвори. В комплекте съёмная брошь из сухоцветов. Zero-waste крой. Коллаборация Click × дизайнер UNA.',
    isAvailable: false,
    cashbackPercent: 5,
    season: 'all',
    yashilMeros: false,
  },

  // ─── АКСЕССУАРЫ ─────────────────────────────────────────────────────────────

  {
    id: 'wallet-keys',
    slug: 'wallet-keys',
    name: 'Кошелёк «Карты Деньги 2 Ключа»',
    nameUz: '«Kartalar, Pullar, 2 Kalit» hamyoni',
    price: 285000,
    image: `${CDN}/e22a341d-8409-4a13-b2b7-6612bcde2231.webp`,
    imageBg: '#f0ede8',
    tag: 'leather',
    collab: 'Мастера Ташкента',
    category: 'leather',
    description: 'Из цельного куска натуральной кожи. Ручная работа ташкентских мастеров. Три отдела — карты, наличные, ключи. Логотип Click тиснением.',
    isAvailable: true,
    cashbackPercent: 3,
    season: 'all',
    yashilMeros: false,
  },
  {
    id: 'cardholder',
    slug: 'cardholder',
    name: 'Картхолдер Click',
    nameUz: 'Click kartxolder',
    price: 32000,
    image: `${CDN}/9dbdbbc7-aff1-4ead-97dc-5d9eac261234.webp`,
    imageBg: '#f0ede8',
    tag: 'new',
    category: 'leather',
    description: 'Компактный картхолдер для кармана или сумки. Механизм быстрого доступа к картам. Доступен в 4 цветах: чёрный, синий, красный, чёрный узор.',
    isAvailable: true,
    cashbackPercent: 3,
    season: 'all',
    yashilMeros: false,
  },
  {
    id: 'avoska-yashil',
    slug: 'avoska-yashil',
    name: 'Авоська Yashil Meros',
    nameUz: 'To\'r xalta | Yashil Meros',
    price: 150000,
    image: `${CDN}/d11e190d-e87a-4609-8b5e-0c243da5f11f.webp`,
    imageBg: '#f0ede8',
    tag: 'eco',
    collab: 'Ручная работа',
    category: 'eco',
    description: 'Рыболовная сетка + винтажная ткань. Вместо пластика. Каждая авоська заменяет ~200 пакетов в год. Складывается в компактный чехол. QR → посадить дерево через Click.',
    isAvailable: true,
    cashbackPercent: 3,
    season: 'all',
    yashilMeros: true,
  },
  {
    id: 'kosynka-dozhevik',
    slug: 'kosynka-dozhevik',
    name: 'Косынка «Дождевик»',
    nameUz: 'Yomg\'irbop Ro\'mol',
    price: 80000,
    image: `${CDN}/def4cfe8-5450-4aa8-a814-0b41dc098260.webp`,
    imageBg: '#f0ede8',
    tag: 'new',
    category: 'accessories',
    description: 'Полупрозрачная косынка-дождевик. Влагостойкий материал. Регулируемые завязки. Защищает причёску от дождя и ветра.',
    isAvailable: true,
    cashbackPercent: 3,
    season: 'all',
    yashilMeros: false,
  },
  {
    id: 'candle-click',
    slug: 'candle-click',
    name: 'Свеча «Click»',
    nameUz: 'Sham "Click"',
    price: 90000,
    image: `${CDN}/48cace4f-a740-4c84-a615-e475b1f610fe.webp`,
    imageBg: '#f0ede8',
    tag: 'new',
    category: 'accessories',
    description: 'Свеча Click. Идеальный подарок.',
    isAvailable: true,
    cashbackPercent: 3,
    season: 'all',
    yashilMeros: false,
  },

  // ─── CLICK TRAVEL ────────────────────────────────────────────────────────────

  {
    id: 'backpack-travel-arka',
    slug: 'backpack-travel-arka',
    name: 'Рюкзак Click Travel «Арка»',
    nameUz: 'Ryukzak Click Travel "Gumbaz"',
    price: 339000,
    image: `${CDN}/product/591301-141367.webp`,
    imageBg: '#f0ede8',
    tag: 'travel',
    category: 'travel',
    collection: 'travel',
    description: 'Рюкзак 20–25 л. Материал: нейлон. Отдельный карман для ноутбука. Принт «Арка» — архитектура Ташкента.',
    isAvailable: true,
    cashbackPercent: 5,
    season: 'all',
    yashilMeros: false,
  },
  {
    id: 'backpack-travel-pamyat',
    slug: 'backpack-travel-pamyat',
    name: 'Рюкзак Click Travel «Память»',
    nameUz: 'Ryukzak Click Travel "Xotira"',
    price: 339000,
    image: `${CDN}/product/591294-722516.webp`,
    imageBg: '#f0ede8',
    tag: 'travel',
    category: 'travel',
    collection: 'travel',
    description: 'Рюкзак 20–25 л. Материал: нейлон. Принт «Память» — узоры Узбекистана.',
    isAvailable: true,
    cashbackPercent: 5,
    season: 'all',
    yashilMeros: false,
  },
  {
    id: 'fanny-travel-arka',
    slug: 'fanny-travel-arka',
    name: 'Бананка Click Travel «Арка»',
    nameUz: 'Bananka Click Travel "Gumbaz"',
    price: 149000,
    image: `${CDN}/product/595318-283672.webp`,
    imageBg: '#f0ede8',
    tag: 'travel',
    category: 'travel',
    collection: 'travel',
    description: 'Поясная сумка из влагостойкой ткани. Универсальный размер. Принт «Арка».',
    isAvailable: true,
    cashbackPercent: 5,
    season: 'all',
    yashilMeros: false,
  },
  {
    id: 'fanny-travel-pamyat',
    slug: 'fanny-travel-pamyat',
    name: 'Бананка Click Travel «Память»',
    nameUz: 'Bananka Click Travel "Xotira"',
    price: 149000,
    image: `${CDN}/product/595299-376870.webp`,
    imageBg: '#f0ede8',
    tag: 'travel',
    category: 'travel',
    collection: 'travel',
    description: 'Поясная сумка из влагостойкой ткани. Универсальный размер. Принт «Память».',
    isAvailable: true,
    cashbackPercent: 5,
    season: 'all',
    yashilMeros: false,
  },
  {
    id: 'shopper-travel-arka',
    slug: 'shopper-travel-arka',
    name: 'Шоппер Click Travel «Арка»',
    nameUz: 'Shopper Click Travel "Gumbaz"',
    price: 99000,
    image: `${CDN}/product/591315-749205.webp`,
    imageBg: '#f0ede8',
    tag: 'travel',
    category: 'travel',
    collection: 'travel',
    description: 'Шоппер 38×42 см, 100% хлопок. Принт «Арка».',
    isAvailable: true,
    cashbackPercent: 3,
    season: 'all',
    yashilMeros: false,
  },
  {
    id: 'shopper-travel-pamyat',
    slug: 'shopper-travel-pamyat',
    name: 'Шоппер Click Travel «Память»',
    nameUz: 'Shopper Click Travel "Xotira"',
    price: 99000,
    image: `${CDN}/product/591308-950725.webp`,
    imageBg: '#f0ede8',
    tag: 'travel',
    category: 'travel',
    collection: 'travel',
    description: 'Шоппер 38×42 см, 100% хлопок. Принт «Память».',
    isAvailable: true,
    cashbackPercent: 3,
    season: 'all',
    yashilMeros: false,
  },
  {
    id: 'bottle-travel-arka',
    slug: 'bottle-travel-arka',
    name: 'Бутылка Click Travel «Арка»',
    nameUz: 'Suv idishi Click Travel "Gumbaz"',
    price: 149000,
    image: `${CDN}/product/591290-657885.webp`,
    imageBg: '#f0ede8',
    tag: 'travel',
    category: 'travel',
    collection: 'travel',
    description: 'Бутылка 500 мл. Материал: soft touch. Принт «Арка».',
    isAvailable: true,
    cashbackPercent: 3,
    season: 'all',
    yashilMeros: false,
  },
  {
    id: 'bottle-travel-pamyat',
    slug: 'bottle-travel-pamyat',
    name: 'Бутылка Click Travel «Память»',
    nameUz: 'Suv idishi Click Travel "Xotira"',
    price: 149000,
    image: `${CDN}/product/591288-669734.webp`,
    imageBg: '#f0ede8',
    tag: 'travel',
    category: 'travel',
    collection: 'travel',
    description: 'Бутылка 500 мл. Материал: soft touch. Принт «Память».',
    isAvailable: false,
    cashbackPercent: 3,
    season: 'all',
    yashilMeros: false,
  },
  {
    id: 'pillow-travel-arka',
    slug: 'pillow-travel-arka',
    name: 'Подушка дорожная Click Travel «Арка»',
    nameUz: 'Yo\'l yostiqchasi Click Travel "Gumbaz"',
    price: 179000,
    image: `${CDN}/product/591273-302280.webp`,
    imageBg: '#f0ede8',
    tag: 'travel',
    category: 'travel',
    collection: 'travel',
    description: 'Дорожная подушка. Хлопок + memory foam. Универсальный размер. Принт «Арка».',
    isAvailable: true,
    cashbackPercent: 3,
    season: 'all',
    yashilMeros: false,
  },
  {
    id: 'pillow-travel-pamyat',
    slug: 'pillow-travel-pamyat',
    name: 'Подушка дорожная Click Travel «Память»',
    nameUz: 'Yo\'l yostiqchasi Click Travel "Xotira"',
    price: 179000,
    image: `${CDN}/product/599713-406038.webp`,
    imageBg: '#f0ede8',
    tag: 'travel',
    category: 'travel',
    collection: 'travel',
    description: 'Дорожная подушка. Хлопок + memory foam. Универсальный размер. Принт «Память».',
    isAvailable: true,
    cashbackPercent: 3,
    season: 'all',
    yashilMeros: false,
  },
  {
    id: 'cap-travel-arka',
    slug: 'cap-travel-arka',
    name: 'Кепка Click Travel «Арка»',
    nameUz: 'Kepka Click Travel "Gumbaz"',
    price: 53900,
    image: `${CDN}/product/591352-707802.webp`,
    imageBg: '#f0ede8',
    tag: 'travel',
    category: 'travel',
    collection: 'travel',
    description: 'Кепка 100% хлопок, регулируемый размер, унисекс. Принт «Арка» — архитектура Ташкента.',
    isAvailable: true,
    cashbackPercent: 3,
    season: 'summer',
    yashilMeros: false,
  },
  {
    id: 'cap-travel-pamyat',
    slug: 'cap-travel-pamyat',
    name: 'Кепка Click Travel «Память»',
    nameUz: 'Kepka Click Travel "Xotira"',
    price: 53900,
    image: `${CDN}/product/591346-134492.webp`,
    imageBg: '#f0ede8',
    tag: 'travel',
    category: 'travel',
    collection: 'travel',
    description: 'Кепка 100% хлопок, регулируемый размер, унисекс. Принт «Память» — узоры Узбекистана.',
    isAvailable: true,
    cashbackPercent: 3,
    season: 'summer',
    yashilMeros: false,
  },
  {
    id: 'panama-travel-arka',
    slug: 'panama-travel-arka',
    name: 'Панама Click Travel «Арка»',
    nameUz: 'Panama Click Travel "Gumbaz"',
    price: 119000,
    image: `${CDN}/product/591340-887516.webp`,
    imageBg: '#f0ede8',
    tag: 'travel',
    category: 'travel',
    collection: 'travel',
    description: 'Панама из плотного хлопка. Универсальный размер. Принт «Арка».',
    isAvailable: true,
    cashbackPercent: 3,
    season: 'summer',
    yashilMeros: false,
  },
  {
    id: 'panama-travel-pamyat',
    slug: 'panama-travel-pamyat',
    name: 'Панама Click Travel «Память»',
    nameUz: 'Panama Click Travel "Xotira"',
    price: 119000,
    image: `${CDN}/product/591332-317697.webp`,
    imageBg: '#f0ede8',
    tag: 'travel',
    category: 'travel',
    collection: 'travel',
    description: 'Панама из плотного хлопка. Универсальный размер. Принт «Память».',
    isAvailable: true,
    cashbackPercent: 3,
    season: 'summer',
    yashilMeros: false,
  },
  {
    id: 'polo-travel-black',
    slug: 'polo-travel-black',
    name: 'Поло Click Travel «Память» / Чёрная',
    nameUz: 'Polo Click Travel "Xotira" / Qora',
    price: 189000,
    image: `${CDN}/product/599723-471496.webp`,
    imageBg: '#f0ede8',
    tag: 'travel',
    category: 'travel',
    collection: 'travel',
    description: 'Поло из хлопка с эластаном. Принт «Память». Цвет: чёрный. Размеры: S/46, M/48, L/50, XL/52, XXL/54.',
    isAvailable: true,
    cashbackPercent: 5,
    season: 'summer',
    yashilMeros: false,
  },
  {
    id: 'polo-travel-white',
    slug: 'polo-travel-white',
    name: 'Поло Click Travel «Память» / Белая',
    nameUz: 'Polo Click Travel "Xotira" / Oq',
    price: 189000,
    image: `${CDN}/product/599728-448493.webp`,
    imageBg: '#f0ede8',
    tag: 'travel',
    category: 'travel',
    collection: 'travel',
    description: 'Поло из хлопка с эластаном. Принт «Память». Цвет: белый. Размеры: S/46, M/48, L/50, XL/52, XXL/54.',
    isAvailable: false,
    cashbackPercent: 5,
    season: 'summer',
    yashilMeros: false,
  },
]

// Только доступные сейчас
export const availableProducts = products.filter(p => p.isAvailable)

// По категориям
export const getProductsByCategory = (category: string) =>
  availableProducts.filter(p => category === 'all' || p.category === category)
